#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer Target
{
	uint value;
};

struct GeometryNode
{
	uint64_t vertices;
	uint64_t indices;
	int texture_index_base_color;
	int texture_index_occlusion;
};

layout(set = 0, binding = 0, scalar) readonly buffer GeometryNodes
{
	GeometryNode nodes[];
};

layout(set = 0, binding = 1, scalar) writeonly buffer Output
{
	uint value;
} output_buffer;

layout(local_size_x = 1) in;

void main()
{
	GeometryNode node = nodes[gl_GlobalInvocationID.x];
	Target vertices = Target(node.vertices);
	Target indices = Target(node.indices);
	output_buffer.value = vertices.value + indices.value;
}
