#!/bin/bash
echo "--- Autogeneration ---"
echo
HARDCODED_CAPTURE_COMMANDS=$(grep -e "VKAPI_CALL trace_vk" src/hardcode_write.cpp | wc -l)
HARDCODED_REPLAY_COMMANDS=$(grep -e "void retrace_vk" src/hardcode_read.cpp | wc -l)
HARDCODED_CAPTURE_STRUCTS=$(grep -e "void write_Vk" src/hardcode_write.cpp | wc -l)
HARDCODED_REPLAY_STRUCTS=$(grep -e "void read_Vk" src/hardcode_read.cpp | wc -l)
GENERATED_CAPTURE_COMMANDS=$(grep -e "VKAPI_CALL trace_vk" generated/write_auto.cpp | wc -l)
GENERATED_REPLAY_COMMANDS=$(grep -e "void retrace_vk" generated/read_auto.cpp | wc -l)
GENERATED_CAPTURE_STRUCTS=$(grep -e "void write_Vk" generated/struct_write_auto.cpp | wc -l)
GENERATED_REPLAY_STRUCTS=$(grep -e "void read_Vk" generated/struct_read_auto.cpp | wc -l)
echo "Hardcoded capture commands: $HARDCODED_CAPTURE_COMMANDS"
echo "Hardcoded replay commands: $HARDCODED_REPLAY_COMMANDS"
echo "Hardcoded capture structs: $HARDCODED_CAPTURE_STRUCTS"
echo "Hardcoded replay structs: $HARDCODED_REPLAY_STRUCTS"
echo "Autogenerated capture commands: $GENERATED_CAPTURE_COMMANDS"
echo "Autogenerated replay commands: $GENERATED_REPLAY_COMMANDS"
echo "Autogenerated capture structs: $GENERATED_CAPTURE_STRUCTS"
echo "Autogenerated replay structs: $GENERATED_REPLAY_STRUCTS"

# TBD:
echo "Total of N out of M commands were autogenerated, which is V%"
echo "Total of N out of M structs were autogenerated, which is V%"
