#!/usr/bin/env python3

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "external", "tracetooltests", "scripts"))

import opencl_spec

HEADER_PATH = os.path.join(ROOT, "generated", "opencl_auto.h")
SOURCE_PATH = os.path.join(ROOT, "generated", "opencl_auto.cpp")

def write_header(commands):
    with open(HEADER_PATH, "w", encoding="utf-8") as output:
        output.write("// This file contains only code auto-generated by opencl.py\n\n")
        output.write("#pragma once\n\n")
        output.write("#include <cstdint>\n")
        output.write("#include <string>\n")
        output.write("#include <unordered_map>\n\n")
        output.write("constexpr uint16_t OPENCL_DICTIONARY_BASE = 0x8000;\n\n")
        output.write("enum opencl_function_id : uint16_t\n{\n")
        for index, command in enumerate(commands):
            output.write(f"\tOPENCL_{command} = {index},\n")
        output.write("};\n\n")
        output.write(
            "const std::unordered_map<std::string, uint16_t>& "
            "opencl_function_table();\n"
        )
        output.write("uint16_t opencl_get_function_id(const char* name);\n")
        output.write("const char* opencl_get_function_name(uint16_t id);\n")

def write_source(commands):
    with open(SOURCE_PATH, "w", encoding="utf-8") as output:
        output.write("// This file contains only code auto-generated by opencl.py\n\n")
        output.write('#include "opencl_auto.h"\n\n')
        output.write(
            "const std::unordered_map<std::string, uint16_t>& "
            "opencl_function_table()\n{\n"
        )
        output.write(
            "\tstatic const std::unordered_map<std::string, uint16_t> table\n\t{\n"
        )
        for command in commands:
            output.write(f'\t\t{{ "{command}", OPENCL_{command} }},\n')
        output.write("\t};\n\treturn table;\n}\n\n")
        output.write("uint16_t opencl_get_function_id(const char* name)\n{\n")
        output.write("\tconst auto& table = opencl_function_table();\n")
        output.write("\tconst auto entry = table.find(name);\n")
        output.write("\tif (entry == table.end()) return UINT16_MAX;\n")
        output.write("\treturn entry->second;\n}\n\n")
        output.write("const char* opencl_get_function_name(uint16_t id)\n{\n")
        output.write("\tswitch (id)\n\t{\n")
        for command in commands:
            output.write(f'\tcase OPENCL_{command}: return "{command}";\n')
        output.write("\tdefault: return \"unknown OpenCL call\";\n")
        output.write("\t}\n}\n")

def main():
    commands = opencl_spec.command_names()
    os.makedirs(os.path.join(ROOT, "generated"), exist_ok=True)
    write_header(commands)
    write_source(commands)

if __name__ == "__main__":
    main()
