// Vulkan trace common code

#pragma once

#include <assert.h>
#include <atomic>
#include <cstdint>
#include <thread>
#include <list>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <cstring>
#include <stdio.h>
#include <deque>

#include "lavamutex.h"
#include "containers.h"
#include "lavatube.h"
#include "filereader.h"
#include "jsoncpp/json/value.h"
#include "replay_screenshot.h"

class lava_file_reader;
using lava_replay_func = void (*)(lava_file_reader&);

enum class cli_step_mode : uint8_t
{
	packets = 0,
	calls = 1,
	function = 2,
};

enum class cli_thread_state : uint8_t
{
	not_started = 0,
	running = 1,
	cli_paused = 2,
	wait_handle = 3,
	wait_barrier = 4,
	wait_fence = 5,
	wait_queue_idle = 6,
	wait_device_idle = 7,
	terminated = 8,
	error_paused = 9,
};

enum class cli_instrument_mode : uint8_t
{
	none = 0,
	whole = 1,
	detailed = 2,
};

enum class cli_marker_placement : uint8_t
{
	none = 0,
	before = 1,
	after = 2,
	both = 3,
};
using lava_markings_observer = void (*)(const change_source&, const VkMarkedOffsetsARM*, void*);

extern lava::mutex sync_mutex;

bool same_change_source(const change_source& a, const change_source& b);
void merge_rewrite_markings(std::list<address_rewrite>& queue, const change_source& source, const VkMarkedOffsetsARM* markings);
void merge_rewrite_markings(std::list<address_rewrite>& queue, const change_source& source, const VkMarkedOffsetsARM* markings, VkObjectType object_type, uint32_t object_index);
void merge_rewrite_markings(std::list<address_rewrite>& queue, const change_source& source, const VkMarkedOffsetsARM* markings, VkObjectType object_type, uint32_t object_index, uint32_t stage_index);

struct output_update_packet
{
	bool valid = false;
	uint8_t instrtype = 0;
	uint32_t device_index = CONTAINER_NULL_VALUE;
	uint32_t object_index = CONTAINER_NULL_VALUE;
	uint64_t header_start = 0;
	uint64_t payload_start = 0;
	uint64_t size = 0;
	uint64_t changed_bytes = 0;
	uint32_t checksum = 0;
	bool checksum_valid = false;
	const VkBaseOutStructure* sptr = nullptr;

	void clear()
	{
		valid = false;
		instrtype = 0;
		device_index = CONTAINER_NULL_VALUE;
		object_index = CONTAINER_NULL_VALUE;
		header_start = 0;
		payload_start = 0;
		size = 0;
		changed_bytes = 0;
		checksum = 0;
		checksum_valid = false;
		sptr = nullptr;
	}
};

struct print_packet_selector
{
	uint32_t packet = UINT32_MAX;
	uint32_t thread = UINT32_MAX;
	bool printed = false;
};

// Only used to unwind replay threads out of stop-aware wait paths during shutdown.
struct replay_stop_requested
{
};

enum class reader_run_type : uint8_t
{
	replay,
	stateful,
	isolated,
};

class lava_reader
{
	friend lava_file_reader;

public:
	lava_reader() {}
	lava_reader(const std::string& path) { init(path); }
	/// Load trace dictionaries, limits, tracking and metadata without opening thread streams.
	void init_metadata(const std::string& path);
	/// Collect immutable information about the outer trace file.
	void collect_trace_file_info(const std::string& path);
	void init(const std::string& path);
	~lava_reader();
	void self_test() const;

	lava_file_reader& file_reader(uint16_t thread_id);

	/// end -1 means play until the end
	void set_frames(int start, int end)
	{
		mStart = start;
		mEnd = end;
		if (mEnd != -1) global_frame_count = end - start;
	}

	bool is_frame_selected(int frame) const
	{
		return mEnd == -1 || (frame >= mStart && frame <= mEnd);
	}

	/// Dump trace information to stdout
	void dump_info();
	const std::string& packed_file() const { return mPackedFile; }
	uint64_t trace_file_size() const { return mTraceFileSize; }
	/// Empty when the filesystem does not expose a file birth time.
	const std::string& trace_file_creation_timestamp() const { return mTraceFileCreationTimestamp; }

	void finalize();
	void request_stop(VkDevice cleanup_device = VK_NULL_HANDLE)
	{
		mStopRequested.store(true, std::memory_order_release);
		if (cleanup_device != VK_NULL_HANDLE)
		{
			const uintptr_t requested = reinterpret_cast<uintptr_t>(cleanup_device);
			uintptr_t expected = 0;
			mCleanupDevice.compare_exchange_strong(expected, requested, std::memory_order_acq_rel);
		}
	}
	bool stop_requested() const { return mStopRequested.load(std::memory_order_acquire); }
	bool cleanup_after_stop();

	std::vector<std::atomic_uint_fast32_t>* thread_packet_numbers = nullptr; // thread local packet numbers

	// This is thread safe since we allocate it all before threading begins.
	address_remapper<trackedobject> device_address_remapping;
	address_remapper<trackedaccelerationstructure> acceleration_structure_address_remapping;

	// Output rewrite queue used during post-processing. First pass entries are ordered by entry time. Second pass entries
	// are ordered by packet number and split into one list for each thread.
	std::list<address_rewrite> global_output_rewrite_queue GUARDED_BY(sync_mutex);

	// Replay-side descriptor blobs generated by vkGetDescriptorEXT. Buffer updates with descriptor markings can
	// consume these to rebuild descriptor buffer contents for the replay device instead of using capture-device bytes.
	std::deque<descriptor_rewrite> pending_descriptor_rewrites GUARDED_BY(sync_mutex);
	std::vector<descriptor_buffer_payload> descriptor_buffer_payloads GUARDED_BY(sync_mutex);

	/// Count of completed global frames. After a frame boundary this is the just-finished frame index plus one.
	std::atomic_int global_frame{ 0 };

	/// Total number of global frames in the trace
	int global_frame_count = 0;

	void set_screenshot_ranges(std::vector<replay_screenshot_range>&& ranges)
	{
		mReplayScreenshots.set_ranges(std::move(ranges));
	}

	void set_screenshot_prefix(std::string&& prefix)
	{
		mReplayScreenshots.set_prefix(std::move(prefix));
	}

	bool screenshots_enabled() const
	{
		return mReplayScreenshots.enabled();
	}

	replay_screenshot_handler& screenshots()
	{
		return mReplayScreenshots;
	}

	void destroy_screenshot_resources()
	{
		mReplayScreenshots.destroy();
	}

	std::vector<std::thread> threads;

	// The dictionary is read from a JSON file and then mapped from their to our function ids.
	std::unordered_map<uint16_t, uint16_t> dictionary;

	/// Select whether we replay Vulkan calls, process the trace statefully without Vulkan, or
	/// decode isolated packets without maintaining replay state. Duplicated into the file reader.
	reader_run_type run_type = reader_run_type::replay;
	bool is_replay() const { return run_type == reader_run_type::replay; }
	bool is_stateful() const { return run_type == reader_run_type::stateful; }
	bool is_isolated() const { return run_type == reader_run_type::isolated; }

	/// Whether this replay pass should emit a rewritten output trace.
	/// Duplicated into the file reader.
	bool write_output = false;

	/// Whether this replay pass should print every packet as JSON.
	bool print_packets = false;
	bool print_add_checksums = false;
	uint32_t print_thread_index = UINT32_MAX;
	std::vector<print_packet_selector> print_selectors;
	uint32_t print_selector_count = 0;
	uint32_t print_max_entries = UINT32_MAX;
	uint32_t print_entry_count = 0;
	lava::mutex print_mutex;

	/// Whether we should abort on less serious errors or just warn
	bool validate = false;

	/// Whether we should run the spirv simulator
	bool simulate = false;

	/// If we are run first or second pass
	int pass = 0;

	// Version numbers are never reset but just keep increasing
	int stored_version_major = 0;
	int stored_version_minor = 0;
	int stored_version_patch = 0;

	/// Set our exit status here if we want to signal something special (eg a skip test value)
	std::atomic_int exit_status { 0 };

	/// A fatal replay error (eg device lost) has aborted the replay. The service stays up so the
	/// final state can still be inspected, and 'status' reports ABORTED until 'stop' finishes.
	bool abort_requested() const;
	/// Human readable reason for a fatal replay abort, empty when not aborted.
	std::string abort_reason() const;
	/// Record a fatal replay error on the given reader and request stop of all replay threads.
	void request_abort(lava_file_reader& reader, VkResult retval);

	// Test-only: simulate the named API call returning this unexpected result once, to exercise
	// result pause handling. Set with LAVATUBE_TEST_RETVAL_RESULT="<function>,<nonzero code>".
	std::string test_retval_result_call;
	std::atomic_int_fast32_t test_retval_result_code{ 0 };

	/// Pruned extension lists stored in metadata.json after capture finalization.
	bool has_stored_instance_requested_extensions = false;
	bool has_stored_device_requested_extensions = false;
	std::vector<std::string> stored_instance_requested_extensions;
	std::vector<std::string> stored_device_requested_extensions;
	bool trace_uses_trace_helpers = false;
	lava_markings_observer markings_observer = nullptr;
	void* markings_observer_data = nullptr;
	bool create_results_file = true;

	// CLI stuff
	std::atomic_int cli_thread{ -1 };
	std::atomic_bool cli_running{ false };
	std::atomic_bool cli_service{ false };
	std::atomic_bool cli_idle_check{ true };
	std::atomic_bool cli_isolate_thread{ false };
	std::atomic_bool cli_command_active{ false };
	/// Number of replayed API calls that returned an unexpected error (error pauses and aborts)
	std::atomic_uint_fast32_t cli_error_count{ 0 };
	std::string cli_response; // response data from cli thread to control thread
	std::atomic_bool cli_params_requested{ false };
	std::atomic_bool cli_params_ready{ false };
	bool cli_pipeline_executable_stats_requested = false;
	std::atomic_bool cli_pipeline_executable_stats_enabled{ false };
	bool cli_memory_budget_requested = false;
	std::atomic_bool cli_memory_budget_enabled{ false };
	bool cli_shader_instrumentation_requested = false;
	std::atomic_bool cli_shader_instrumentation_enabled{ false };
	bool device_fault_report_requested = false;
	void* aftermath_context = nullptr;
	void (*aftermath_device_lost_callback)(void*) = nullptr;
	void (*aftermath_register_marker_callback)(void*, const void*, const char*) = nullptr;
	lava::mutex replay_submission_mutex;
	struct replay_address_binding
	{
		VkDeviceAddress base_address = 0;
		VkDeviceSize size = 0;
		VkDeviceAddressBindingFlagsEXT flags = 0;
	};
	lava::mutex device_address_binding_mutex;
	// TODO: The debug-utils callback has no device handle, so bindings cannot yet be attributed per device.
	std::vector<replay_address_binding> replay_address_bindings;
	VkDebugUtilsMessengerEXT device_address_binding_messenger = VK_NULL_HANDLE;
	std::atomic<cli_instrument_mode> cli_instrument_requested{ cli_instrument_mode::none };
	std::atomic_bool cli_instrument_ready{ false };
	std::atomic<cli_marker_placement> cli_marker_requested{ cli_marker_placement::none };
	std::atomic_bool cli_marker_ready{ false };
	std::atomic_uint32_t cli_marker_next_session{ 1 };

private:
	/// Start time of frame range
	std::atomic_uint64_t mStartTime{ 0 };
	std::atomic_bool mStopRequested{ false };
	std::atomic_uintptr_t mCleanupDevice{ 0 };
	mutable lava::mutex mAbortMutex;
	bool mAbortRequested = false;
	std::string mAbortReason;
	/// Start CPU usage for whole process
	struct timespec process_cpu_usage;
	std::string mPackedFile;
	uint64_t mTraceFileSize = 0;
	std::string mTraceFileCreationTimestamp;
	std::vector<lava_file_reader*> thread_streams;
	int mStart = 0;
	int mEnd = -1;
	FILE* out_fptr = nullptr;
	replay_screenshot_handler mReplayScreenshots;
};

class lava_file_reader : public file_reader
{
	lava_file_reader(const lava_file_reader&) = delete;
	lava_file_reader& operator=(const lava_file_reader&) = delete;

public:
	/// Initialize one thread of replay. Frame start and end values are global, not local. Frames are either (end-start)
	/// or total number of global frames in the trace.
	lava_file_reader(lava_reader* _parent, const std::string& path, int mytid, int frames, const Json::Value& frameinfo, size_t uncompressed_size, size_t uncompressed_wanted, int start = 0, int end = -1);
	/// Decode one caller-owned, uncompressed packet without constructing a streaming file reader.
	lava_file_reader(lava_reader* _parent, const char* packet, size_t packet_size, int mytid,
		uint32_t packet_index, uint32_t frame, uint8_t stored_stream_version);
	~lava_file_reader();
	void reset_fixed_packet(const char* packet, size_t packet_size, uint32_t packet_index,
		uint32_t frame, uint8_t stored_stream_version);

	/// Returns zero if no more instructions in the file, or the instruction type found.
	uint8_t step();
	void complete_packet();

	VkFlags read_VkFlags() { uint32_t t; read_value(&t); return static_cast<VkFlags>(t); }

	inline int thread_index() const { return current.thread; }
	inline uint64_t stream_position() const { return read_position; }
	inline const char* stream_data(uint64_t pos) const { return uncompressed_data + pos; }
	inline uint64_t packet_start() const { return current_packet_start; }
	inline uint64_t packet_end() const { return current_packet_end; }
	inline uint32_t packet_size() const { return current_packet_size; }
	void bind_trace_thread_name() const
	{
		if (trace_thread_name[0] != '\0') set_thread_name(trace_thread_name);
	}
	const char* get_trace_thread_name() const
	{
		return trace_thread_name[0] != '\0' ? trace_thread_name : "-";
	}

	void note_markings(const VkMarkedOffsetsARM* markings);

	inline VkDescriptorDataEXT read_VkDescriptorDataEXT() { return VkDescriptorDataEXT{}; } // TBD
	inline VkAccelerationStructureNV read_VkAccelerationStructureNV() { return VK_NULL_HANDLE; }

	inline uint32_t read_handle(DEBUGPARAM(const char* name));
#ifdef DEBUG
	inline void read_handle_array(const char* name, uint32_t* dest, uint32_t length) { for (uint32_t i = 0; i < length; i++) dest[i] = read_handle(name); }
#else
	inline void read_handle_array(uint32_t* dest, uint32_t length) { for (uint32_t i = 0; i < length; i++) dest[i] = read_handle(); }
#endif
	inline void read_barrier();
	const std::vector<unsigned>& barrier_packet_indices() const { return current_barrier_packet_indices; }
	uint16_t read_apicall();

	bool start_measurement_on_thread_entry() const
	{
		return !mUseFrameRange;
	}

	/// Read patch update and track host side changes
	uint32_t read_patch_tracking(char* buf, uint64_t maxsize, host_write_regions& regions,
		VkObjectType object_type = VK_OBJECT_TYPE_UNKNOWN, uint32_t object_index = CONTAINER_NULL_VALUE)
	{
		char* ptr = buf;
		uint32_t offset;
		uint32_t size;
		uint64_t changed = 0;
		do {
			offset = read_uint32_t();
			ptr += offset;
			// cppcheck-suppress nullPointerRedundantCheck
			assert(maxsize == 0 || ptr <= buf + maxsize);
			size = read_uint32_t();
			check_space(size);
			const char* uptr = uncompressed_data + read_position;
			if (buf && size)
			{
				memcpy(ptr, uptr, size);
				const VkDeviceSize base_offset = (VkDeviceSize)(ptr - buf);
				regions.register_source(base_offset, size, current, 1, 0, object_type, object_index);
			}
			read_position += size;
			ptr += size;
			changed += size;
			// cppcheck-suppress nullPointerRedundantCheck
			assert(maxsize == 0 || ptr <= buf + maxsize);
		}
		while (!(offset == 0 && size == 0));
		return changed;
	}

	/// If this one returns true, we are responsible for cleaning up all Vulkan calls and then exiting.
	bool new_frame()
	{
		if (mStart == (int)current.frame)
		{
			parent->mStartTime.store(gettime());
			if (mHaveFirstFrame)
			{
				ILOG("==== starting frame frange ====");
				if (clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &parent->process_cpu_usage) != 0)
				{
					ELOG("Failed to get process CPU usage: %s", strerror(errno));
				}
			}
			start_measurement();
		}
		current.frame++;
		parent->global_frame++;
		// The measurement window starts at the selected start boundary, so stop
		// after replaying the selected end boundary to cover end - start intervals.
		if (mEnd != -1 && (int)current.frame == mEnd + 1)
		{
			if (mHaveFinalFrame)
			{
				return true;
			}
		}
		return false;
	}

	lava_reader* parent;
	VkDevice device = VK_NULL_HANDLE;
	VkPhysicalDevice physicalDevice = VK_NULL_HANDLE;
	// Keep throw sites tightly scoped to cooperative replay shutdown waits.
	[[noreturn]] void throw_stop_requested() const { throw replay_stop_requested{}; }

	/// Select whether we replay Vulkan calls, process the trace statefully without Vulkan, or
	/// decode an isolated packet without maintaining replay state.
	reader_run_type run_type = reader_run_type::replay;
	bool is_replay() const { return run_type == reader_run_type::replay; }
	bool is_stateful() const { return run_type == reader_run_type::stateful; }
	bool is_isolated() const { return run_type == reader_run_type::isolated; }
	bool write_output = false;
	bool printed_current_packet = false;
	uint32_t print_packet_frame = 0;
	uint32_t print_packet_number = 0;
	uint32_t api_call_count = 0;

	// CLI stuff
	std::atomic_uint_fast32_t cli_call{ UINT32_MAX };
	std::atomic_uint_fast32_t cli_paused_call{ 0 };
	std::atomic_uint_fast32_t cli_packet{ 0 };
	std::atomic_uint_fast16_t cli_function{ UINT16_MAX };
	std::atomic<cli_step_mode> cli_step{ cli_step_mode::packets };
	std::atomic<cli_thread_state> cli_state{ cli_thread_state::not_started };
	std::atomic_uint_fast32_t cli_pause_generation{ 0 };
	std::atomic_int_fast16_t cli_wait_thread{ -1 };
	std::atomic_uint_fast32_t cli_wait_packet{ UINT32_MAX };
	std::atomic_uint_fast32_t cli_wait_object_type{ VK_OBJECT_TYPE_UNKNOWN };
	std::atomic_uint_fast32_t cli_wait_object_index{ CONTAINER_INVALID_INDEX };
	std::atomic_uint_fast32_t cli_wait_aux_index{ CONTAINER_INVALID_INDEX };
	/// Unexpected API result mark from check_retval: the packet where the error was seen and the
	/// error code itself. Consumed by check_cli(), which turns it into an error pause.
	std::atomic_uint_fast32_t cli_error_packet{ UINT32_MAX };
	std::atomic_int_fast32_t cli_error_mark{ 0 };
	/// Unexpected API result at the current pause point, reported by 'status' (0 = none)
	std::atomic_int_fast32_t cli_paused_error{ 0 };

	// Replay-only: per-thread queue for AS build sizes and internal AS buffers.
	std::deque<VkAccelerationStructureBuildSizesInfoKHR> pending_as_build_sizes;
	std::deque<internal_buffer> pending_as_storage_buffers;

	/// Is this reader's thread terminated?
	std::atomic_bool terminated{ false };

	/// Rewrite queue for the second pass, re-sorted and split by thread.
	std::list<address_rewrite> rewrite_queue;
	output_update_packet current_update_packet;
	bool current_packet_contains_shader_data = false;

	change_source current;

	void self_test() const
	{
		assert(parent);
		assert(run_type == parent->run_type);
		assert(write_output == parent->write_output);
		assert(global_frames >= local_frames);
		file_reader::self_test();
	}

private:
	bool mUseFrameRange = false;
	int mStart = -1; ///< Local start frame
	int mEnd = -1; ///< Local end frame
	/// Do we own the final global frame?
	bool mHaveFinalFrame = false;
	/// Do we own the first global frame?
	bool mHaveFirstFrame = false;
	/// Total amount of global frames (for final FPS calculation)
	unsigned global_frames = 0;
	unsigned local_frames = 0;
	char trace_thread_name[16] = {};
	bool current_packet_open = false;
	uint64_t current_packet_start = 0;
	uint64_t current_packet_end = 0;
	uint32_t current_packet_size = 0;
	std::vector<unsigned> current_barrier_packet_indices;
	struct print_frame_boundary
	{
		uint64_t position = 0;
		uint32_t next_frame = 0;
	};
	std::vector<print_frame_boundary> print_frame_boundaries;
	size_t next_print_frame_boundary = 0;
	uint32_t isolated_print_frame = 0;
};

inline void lava_file_reader::read_barrier()
{
	const unsigned size = read_uint8_t();
	current_barrier_packet_indices.resize(size);
	for (int i = 0; i < (int)size; i++)
	{
		current_barrier_packet_indices[i] = read_uint32_t();
		assert(current_barrier_packet_indices[i] != UINT32_MAX);
	}
	complete_packet();
	if (is_isolated()) return;
	for (int i = 0; i < (int)size; i++)
	{
		const unsigned packet_index = current_barrier_packet_indices[i];
		DLOG3("Thread barrier on thread %d, waiting for packet %u on thread %d / %u", current.thread, packet_index, i, size - 1);
		const bool publish_wait = i != current.thread && packet_index > parent->thread_packet_numbers->at(i).load(std::memory_order_relaxed) && parent->cli_service.load(std::memory_order_acquire);
		if (publish_wait)
		{
			cli_wait_thread.store(i, std::memory_order_relaxed);
			cli_wait_packet.store(packet_index, std::memory_order_relaxed);
			cli_state.store(cli_thread_state::wait_barrier, std::memory_order_release);
		}
		while (i != current.thread && packet_index > parent->thread_packet_numbers->at(i).load(std::memory_order_relaxed))
		{
			if (parent->stop_requested()) throw_stop_requested();
			usleep(1);
		}
		if (publish_wait) cli_state.store(cli_thread_state::running, std::memory_order_release);
	}
	DLOG2("[t%02d] Passed thread barrier, waited for %u threads", (int)current.thread, size);
}

inline uint32_t lava_file_reader::read_handle(DEBUGPARAM(const char* name))
{
	const uint32_t index = read_uint32_t();
	const int req_thread = read_int8_t();
	const uint32_t req_packet = read_uint32_t();
	if (is_isolated() || req_thread < 0 || req_thread == (int)current.thread)
	{
		DLOG2("[t%02d %06d] read handle %s index=%u from same thread", (int)current.thread, (int)current.packet + 1, name, (unsigned)index);
		return index;
	}
	// check for thread dependency, if we need a resource not provided yet, spin until it is
	uint32_t completed_packets = parent->thread_packet_numbers->at(req_thread).load(std::memory_order_relaxed);
#ifdef DEBUG
	if (req_packet < completed_packets) DLOG2("[t%02d %06d] read handle %s index=%u, was for tid=%d packet=%u, it is already at packet=%u", (int)current.thread, (int)current.packet + 1, name, (unsigned)index, (int)req_thread, req_packet, completed_packets);
	else DLOG2("[t%02d %06d] read handle %s index=%u, MUST WAIT for tid=%d packet=%u, it is now at packet=%u", (int)current.thread, (int)current.packet + 1, name, (unsigned)index, (int)req_thread, req_packet, completed_packets);
#endif
	const bool publish_wait = req_packet >= completed_packets && parent->cli_service.load(std::memory_order_acquire);
	if (publish_wait)
	{
		cli_wait_thread.store(req_thread, std::memory_order_relaxed);
		cli_wait_packet.store(req_packet, std::memory_order_relaxed);
		cli_state.store(cli_thread_state::wait_handle, std::memory_order_release);
	}
	while (req_packet >= completed_packets)
	{
		if (parent->stop_requested()) throw_stop_requested();
		usleep(1);
		completed_packets = parent->thread_packet_numbers->at(req_thread).load(std::memory_order_relaxed);
	}
	if (publish_wait) cli_state.store(cli_thread_state::running, std::memory_order_release);
	return index;
}

static inline bool check_cli(const callback_context& cb)
{
	lava_reader* parent = cb.reader.parent;
	int req_thread = parent->cli_thread.load(std::memory_order_acquire);
	if (req_thread == -1) return false; // fast out if not running under CLI control
	if (parent->stop_requested()) cb.reader.throw_stop_requested();
	// A replayed API call on this thread returned an unexpected error: force an error pause so
	// lava-cli can inspect the state. If the replay is already paused elsewhere, or another
	// thread's error won the race, the error stays reported through the log and error count.
	const int_fast32_t error_retval = cb.reader.cli_error_mark.load(std::memory_order_acquire);
	if (error_retval != 0)
	{
		if (cb.reader.cli_error_packet.load(std::memory_order_acquire) != cb.reader.current.packet)
		{
			cb.reader.cli_error_mark.store(0, std::memory_order_release); // stale mark from a skipped epilogue
		}
		else
		{
			int expected = req_thread;
			const bool takeover = parent->cli_running.load(std::memory_order_acquire)
				&& (expected == (int)cb.reader.current.thread
				    || parent->cli_thread.compare_exchange_strong(expected, (int)cb.reader.current.thread, std::memory_order_acq_rel, std::memory_order_acquire));
			cb.reader.cli_error_mark.store(0, std::memory_order_release);
			if (!takeover)
			{
				cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
				return false;
			}
			uint32_t completed_call = 0;
			const cli_step_mode step_mode = cb.reader.cli_step.load(std::memory_order_acquire);
			if (step_mode == cli_step_mode::calls || step_mode == cli_step_mode::function) completed_call = cb.reader.api_call_count + 1;
			else completed_call = cb.reader.cli_packet.load(std::memory_order_relaxed) + 1;
			cb.reader.cli_paused_call.store(completed_call, std::memory_order_release);
			cb.reader.cli_paused_error.store(error_retval, std::memory_order_release);
			cb.reader.cli_state.store(cli_thread_state::error_paused, std::memory_order_release);
			cb.reader.cli_pause_generation.fetch_add(1, std::memory_order_acq_rel);
			cb.reader.cli_pause_generation.notify_all();
			parent->cli_running.store(false, std::memory_order_release);
			parent->cli_running.notify_all();
			usleep(50);
			return true; // loop in caller until lava-cli resolves the error pause
		}
	}
	// An error on another thread may have retargeted the selected thread
	req_thread = parent->cli_thread.load(std::memory_order_acquire);
	bool selected_thread = req_thread == cb.reader.current.thread;
	if (!selected_thread)
	{
		if (parent->cli_isolate_thread.load(std::memory_order_acquire))
		{
			cb.reader.cli_state.store(cli_thread_state::cli_paused, std::memory_order_release);
			while (parent->cli_isolate_thread.load(std::memory_order_acquire)
			       && parent->cli_thread.load(std::memory_order_acquire) != (int)cb.reader.current.thread)
			{
				if (parent->stop_requested()) cb.reader.throw_stop_requested();
				usleep(50);
			}
		}
		cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
		return false;
	}
	const bool keep_error_pause = cb.reader.cli_state.load(std::memory_order_acquire) == cli_thread_state::error_paused;
	if (parent->cli_running.load(std::memory_order_acquire))
	{
		uint32_t completed_call = 0;
		const cli_step_mode step_mode = cb.reader.cli_step.load(std::memory_order_acquire);
		if (step_mode == cli_step_mode::calls || step_mode == cli_step_mode::function)
		{
			if (cb.reader.current.packet_type != PACKET_VULKAN_API_CALL)
			{
				cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
				return false;
			}
			if (step_mode == cli_step_mode::function && cb.reader.current.call_id != cb.reader.cli_function.load(std::memory_order_acquire))
			{
				cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
				return false;
			}
			completed_call = cb.reader.api_call_count + 1;
		}
		else
		{
			completed_call = cb.reader.cli_packet.load(std::memory_order_relaxed) + 1;
		}
		const uint32_t req_call = cb.reader.cli_call.load(std::memory_order_acquire);
		if (completed_call < req_call)
		{
			cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
			return false;
		}
		cb.reader.cli_paused_call.store(completed_call, std::memory_order_release);
	}
	// An error pause is a normal pause that remembers its unexpected result; the epilogue's
	// check_cli spin would otherwise clear it, so keep the state and error on re-entry.
	if (!keep_error_pause) cb.reader.cli_paused_error.store(0, std::memory_order_release);
	cb.reader.cli_state.store(keep_error_pause ? cli_thread_state::error_paused : cli_thread_state::cli_paused, std::memory_order_release);
	cb.reader.cli_pause_generation.fetch_add(1, std::memory_order_acq_rel);
	cb.reader.cli_pause_generation.notify_all();
	parent->cli_running.store(false, std::memory_order_release);
	parent->cli_running.notify_all();
	usleep(50);
	return true; // loop in caller until lava-cli resumes replay
}

Json::Value cli_params_base_json(const callback_context& cb);
Json::Value cli_params_attachment(const callback_context& cb);
void cli_params_publish(callback_context& cb, Json::Value v);
void cli_params_unavailable(callback_context& cb);
void cli_params_packet(callback_context& cb);
bool print_params_requested(callback_context& cb);
void print_params_publish(callback_context& cb, Json::Value v);
void print_params_unavailable(callback_context& cb);
void print_params_packet(callback_context& cb);

/// Validate that a replayed API call returned a result compatible with what the captured app saw.
/// A mismatch is an abort outside replay service mode; in service mode a non-fatal result is
/// reported to lava-cli as an error pause, and a fatal error (device lost) aborts the replay while
/// keeping the service reachable. The result is passed by reference for the test-only override.
void check_retval(lava_file_reader& reader, VkResult stored_retval, VkResult& retval);
