// Vulkan trace common code

#pragma once

#include <assert.h>
#include <atomic>
#include <cstdint>
#include <thread>
#include <list>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <cstring>
#include <stdio.h>
#include <deque>

#include "lavamutex.h"
#include "containers.h"
#include "lavatube.h"
#include "filereader.h"
#include "jsoncpp/json/value.h"
#include "replay_screenshot.h"

class lava_file_reader;
using lava_replay_func = void (*)(lava_file_reader&);

enum class cli_step_mode : uint8_t
{
	packets = 0,
	calls = 1,
	function = 2,
};

enum class cli_thread_state : uint8_t
{
	not_started = 0,
	running = 1,
	cli_paused = 2,
	wait_handle = 3,
	wait_barrier = 4,
	wait_fence = 5,
	wait_queue_idle = 6,
	wait_device_idle = 7,
	terminated = 8,
};
using lava_markings_observer = void (*)(const change_source&, const VkMarkedOffsetsARM*, void*);

extern lava::mutex sync_mutex;

bool same_change_source(const change_source& a, const change_source& b);
void merge_rewrite_markings(std::list<address_rewrite>& queue, const change_source& source, const VkMarkedOffsetsARM* markings);
void merge_rewrite_markings(std::list<address_rewrite>& queue, const change_source& source, const VkMarkedOffsetsARM* markings, VkObjectType object_type, uint32_t object_index);
void merge_rewrite_markings(std::list<address_rewrite>& queue, const change_source& source, const VkMarkedOffsetsARM* markings, VkObjectType object_type, uint32_t object_index, uint32_t stage_index);

struct output_update_packet
{
	bool valid = false;
	uint8_t instrtype = 0;
	uint32_t device_index = CONTAINER_NULL_VALUE;
	uint32_t object_index = CONTAINER_NULL_VALUE;
	uint64_t header_start = 0;
	uint64_t payload_start = 0;
	uint64_t size = 0;
	const VkBaseOutStructure* sptr = nullptr;

	void clear()
	{
		valid = false;
		instrtype = 0;
		device_index = CONTAINER_NULL_VALUE;
		object_index = CONTAINER_NULL_VALUE;
		header_start = 0;
		payload_start = 0;
		size = 0;
		sptr = nullptr;
	}
};

struct print_packet_selector
{
	uint32_t packet = UINT32_MAX;
	uint32_t thread = UINT32_MAX;
	bool printed = false;
};

// Only used to unwind replay threads out of stop-aware wait paths during shutdown.
struct replay_stop_requested
{
};

class lava_reader
{
	friend lava_file_reader;

public:
	lava_reader() {}
	lava_reader(const std::string& path) { init(path); }
	void init(const std::string& path);
	~lava_reader();

	lava_file_reader& file_reader(uint16_t thread_id);

	/// end -1 means play until the end
	void set_frames(int start, int end)
	{
		mStart = start;
		mEnd = end;
		if (mEnd != -1) global_frame_count = end - start;
	}

	bool is_frame_selected(int frame) const
	{
		return mEnd == -1 || (frame >= mStart && frame <= mEnd);
	}

	/// Dump trace information to stdout
	void dump_info();
	const std::string& packed_file() const { return mPackedFile; }

	void finalize();
	void request_stop(VkDevice cleanup_device = VK_NULL_HANDLE)
	{
		mStopRequested.store(true, std::memory_order_release);
		if (cleanup_device != VK_NULL_HANDLE)
		{
			const uintptr_t requested = reinterpret_cast<uintptr_t>(cleanup_device);
			uintptr_t expected = 0;
			mCleanupDevice.compare_exchange_strong(expected, requested, std::memory_order_acq_rel);
		}
	}
	bool stop_requested() const { return mStopRequested.load(std::memory_order_acquire); }
	bool cleanup_after_stop();

	std::vector<std::atomic_uint_fast32_t>* thread_packet_numbers; // thread local packet numbers

	// This is thread safe since we allocate it all before threading begins.
	address_remapper<trackedobject> device_address_remapping;
	address_remapper<trackedaccelerationstructure> acceleration_structure_address_remapping;

	// Output rewrite queue used during post-processing. First pass entries are ordered by entry time. Second pass entries
	// are ordered by packet number and split into one list for each thread.
	std::list<address_rewrite> global_output_rewrite_queue GUARDED_BY(sync_mutex);

	// Replay-side descriptor blobs generated by vkGetDescriptorEXT. Buffer updates with descriptor markings can
	// consume these to rebuild descriptor buffer contents for the replay device instead of using capture-device bytes.
	std::deque<descriptor_rewrite> pending_descriptor_rewrites GUARDED_BY(sync_mutex);
	std::vector<descriptor_buffer_payload> descriptor_buffer_payloads GUARDED_BY(sync_mutex);

	/// Count of completed global frames. After a frame boundary this is the just-finished frame index plus one.
	std::atomic_int global_frame{ 0 };

	/// Total number of global frames in the trace
	int global_frame_count = 0;

	void set_screenshot_ranges(std::vector<replay_screenshot_range>&& ranges)
	{
		mReplayScreenshots.set_ranges(std::move(ranges));
	}

	void set_screenshot_prefix(std::string&& prefix)
	{
		mReplayScreenshots.set_prefix(std::move(prefix));
	}

	bool screenshots_enabled() const
	{
		return mReplayScreenshots.enabled();
	}

	replay_screenshot_handler& screenshots()
	{
		return mReplayScreenshots;
	}

	void destroy_screenshot_resources()
	{
		mReplayScreenshots.destroy();
	}

	std::vector<std::thread> threads;

	// The dictionary is read from a JSON file and then mapped from their to our function ids.
	std::unordered_map<uint16_t, uint16_t> dictionary;

	/// Whether we should actually call into Vulkan or if we are just processing the data.
	/// Duplicated into the file reader.
	bool run = true;

	/// Whether this replay pass should emit a rewritten output trace.
	/// Duplicated into the file reader.
	bool write_output = false;

	/// Whether this replay pass should print every packet as JSON.
	bool print_packets = false;
	uint32_t print_thread_index = UINT32_MAX;
	std::vector<print_packet_selector> print_selectors;
	uint32_t print_selector_count = 0;
	uint32_t print_max_entries = UINT32_MAX;
	uint32_t print_entry_count = 0;
	lava::mutex print_mutex;

	/// Whether we should abort on less serious errors or just warn
	bool validate = false;

	/// Whether we should run the spirv simulator
	bool simulate = false;

	/// If we are run first or second pass
	int pass = 0;

	// Version numbers are never reset but just keep increasing
	int stored_version_major = 0;
	int stored_version_minor = 0;
	int stored_version_patch = 0;

	/// Set our exit status here if we want to signal something special (eg a skip test value)
	std::atomic_int exit_status { 0 };

	/// Pruned extension lists stored in metadata.json after capture finalization.
	bool has_stored_instance_requested_extensions = false;
	bool has_stored_device_requested_extensions = false;
	std::vector<std::string> stored_instance_requested_extensions;
	std::vector<std::string> stored_device_requested_extensions;
	bool trace_uses_trace_helpers = false;
	lava_markings_observer markings_observer = nullptr;
	void* markings_observer_data = nullptr;
	bool create_results_file = true;

	// CLI stuff
	std::atomic_int cli_thread{ -1 };
	std::atomic_bool cli_running{ false };
	std::atomic_bool cli_service{ false };
	std::atomic_bool cli_command_active{ false };
	std::string cli_response; // response data from cli thread to control thread
	std::atomic_bool cli_params_requested{ false };
	std::atomic_bool cli_params_ready{ false };
	bool cli_pipeline_executable_stats_requested = false;
	std::atomic_bool cli_pipeline_executable_stats_enabled{ false };
	bool cli_memory_budget_requested = false;
	std::atomic_bool cli_memory_budget_enabled{ false };

private:
	/// Start time of frame range
	std::atomic_uint64_t mStartTime{ 0 };
	std::atomic_bool mStopRequested{ false };
	std::atomic_uintptr_t mCleanupDevice{ 0 };
	/// Start CPU usage for whole process
	struct timespec process_cpu_usage;
	std::string mPackedFile;
	std::vector<lava_file_reader*> thread_streams;
	int mStart = 0;
	int mEnd = -1;
	FILE* out_fptr = nullptr;
	replay_screenshot_handler mReplayScreenshots;
};

class lava_file_reader : public file_reader
{
	lava_file_reader(const lava_file_reader&) = delete;
	lava_file_reader& operator=(const lava_file_reader&) = delete;

public:
	/// Initialize one thread of replay. Frame start and end values are global, not local. Frames are either (end-start)
	/// or total number of global frames in the trace.
	lava_file_reader(lava_reader* _parent, const std::string& path, int mytid, int frames, const Json::Value& frameinfo, size_t uncompressed_size, size_t uncompressed_wanted, int start = 0, int end = -1);
	~lava_file_reader();

	/// Returns zero if no more instructions in the file, or the instruction type found.
	uint8_t step();
	void complete_packet();

	VkFlags read_VkFlags() { uint32_t t; read_value(&t); return static_cast<VkFlags>(t); }

	inline int thread_index() const { return current.thread; }
	inline uint64_t stream_position() const { return read_position; }
	inline const char* stream_data(uint64_t pos) const { return uncompressed_data + pos; }
	inline uint64_t packet_start() const { return current_packet_start; }
	inline uint64_t packet_end() const { return current_packet_end; }
	inline uint32_t packet_size() const { return current_packet_size; }
	void bind_trace_thread_name() const
	{
		if (trace_thread_name[0] != '\0') set_thread_name(trace_thread_name);
	}
	const char* get_trace_thread_name() const
	{
		return trace_thread_name[0] != '\0' ? trace_thread_name : "-";
	}

	void note_markings(const VkMarkedOffsetsARM* markings);

	inline VkDescriptorDataEXT read_VkDescriptorDataEXT() { return VkDescriptorDataEXT{}; } // TBD
	inline VkAccelerationStructureNV read_VkAccelerationStructureNV() { return VK_NULL_HANDLE; }

	inline uint32_t read_handle(DEBUGPARAM(const char* name));
#ifdef DEBUG
	inline void read_handle_array(const char* name, uint32_t* dest, uint32_t length) { for (uint32_t i = 0; i < length; i++) dest[i] = read_handle(name); }
#else
	inline void read_handle_array(uint32_t* dest, uint32_t length) { for (uint32_t i = 0; i < length; i++) dest[i] = read_handle(); }
#endif
	inline void read_barrier();
	uint16_t read_apicall();

	bool start_measurement_on_thread_entry() const
	{
		return !mUseFrameRange;
	}

	/// Read patch update and track host side changes
	uint32_t read_patch_tracking(char* buf, uint64_t maxsize, host_write_regions& regions,
		VkObjectType object_type = VK_OBJECT_TYPE_UNKNOWN, uint32_t object_index = CONTAINER_NULL_VALUE)
	{
		char* ptr = buf;
		uint32_t offset;
		uint32_t size;
		uint64_t changed = 0;
		do {
			offset = read_uint32_t();
			ptr += offset;
			// cppcheck-suppress nullPointerRedundantCheck
			assert(maxsize == 0 || ptr <= buf + maxsize);
			size = read_uint32_t();
			check_space(size);
			const char* uptr = uncompressed_data + read_position;
			if (buf && size)
			{
				memcpy(ptr, uptr, size);
				const VkDeviceSize base_offset = (VkDeviceSize)(ptr - buf);
				regions.register_source(base_offset, size, current, 1, 0, object_type, object_index);
			}
			read_position += size;
			ptr += size;
			changed += size;
			// cppcheck-suppress nullPointerRedundantCheck
			assert(maxsize == 0 || ptr <= buf + maxsize);
		}
		while (!(offset == 0 && size == 0));
		return changed;
	}

	/// If this one returns true, we are responsible for cleaning up all Vulkan calls and then exiting.
	bool new_frame()
	{
		if (mStart == (int)current.frame)
		{
			parent->mStartTime.store(gettime());
			if (mHaveFirstFrame)
			{
				ILOG("==== starting frame frange ====");
				if (clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &parent->process_cpu_usage) != 0)
				{
					ELOG("Failed to get process CPU usage: %s", strerror(errno));
				}
			}
			start_measurement();
		}
		current.frame++;
		parent->global_frame++;
		// The measurement window starts at the selected start boundary, so stop
		// after replaying the selected end boundary to cover end - start intervals.
		if (mEnd != -1 && (int)current.frame == mEnd + 1)
		{
			if (mHaveFinalFrame)
			{
				return true;
			}
		}
		return false;
	}

	lava_reader* parent;
	VkDevice device = VK_NULL_HANDLE;
	VkPhysicalDevice physicalDevice = VK_NULL_HANDLE;
	// Keep throw sites tightly scoped to cooperative replay shutdown waits.
	[[noreturn]] void throw_stop_requested() const { throw replay_stop_requested{}; }

	/// Whether we should actually call into Vulkan or if we are just processing the data
	bool run = true;
	bool write_output = false;
	bool printed_current_packet = false;
	uint32_t print_packet_frame = 0;
	uint32_t print_packet_number = 0;
	uint32_t api_call_count = 0;

	// CLI stuff
	std::atomic_uint_fast32_t cli_call{ UINT32_MAX };
	std::atomic_uint_fast32_t cli_paused_call{ 0 };
	std::atomic_uint_fast32_t cli_packet{ 0 };
	std::atomic_uint_fast16_t cli_function{ UINT16_MAX };
	std::atomic<cli_step_mode> cli_step{ cli_step_mode::packets };
	std::atomic<cli_thread_state> cli_state{ cli_thread_state::not_started };
	std::atomic_uint_fast32_t cli_pause_generation{ 0 };
	std::atomic_int_fast16_t cli_wait_thread{ -1 };
	std::atomic_uint_fast32_t cli_wait_packet{ UINT32_MAX };
	std::atomic_uint_fast32_t cli_wait_object_type{ VK_OBJECT_TYPE_UNKNOWN };
	std::atomic_uint_fast32_t cli_wait_object_index{ CONTAINER_INVALID_INDEX };
	std::atomic_uint_fast32_t cli_wait_aux_index{ CONTAINER_INVALID_INDEX };

	// Replay-only: per-thread queue for AS build sizes and internal AS buffers.
	std::deque<VkAccelerationStructureBuildSizesInfoKHR> pending_as_build_sizes;
	std::deque<internal_buffer> pending_as_storage_buffers;

	/// Is this reader's thread terminated?
	std::atomic_bool terminated{ false };

	/// Rewrite queue for the second pass, re-sorted and split by thread.
	std::list<address_rewrite> rewrite_queue;
	output_update_packet current_update_packet;

	change_source current;

	void self_test() const
	{
		assert(parent);
		assert(run == parent->run);
		assert(write_output == parent->write_output);
		assert(global_frames >= local_frames);
		file_reader::self_test();
	}

private:
	bool mUseFrameRange = false;
	int mStart = -1; ///< Local start frame
	int mEnd = -1; ///< Local end frame
	/// Do we own the final global frame?
	bool mHaveFinalFrame = false;
	/// Do we own the first global frame?
	bool mHaveFirstFrame = false;
	/// Total amount of global frames (for final FPS calculation)
	unsigned global_frames = 0;
	unsigned local_frames = 0;
	char trace_thread_name[16] = {};
	bool current_packet_open = false;
	uint64_t current_packet_start = 0;
	uint64_t current_packet_end = 0;
	uint32_t current_packet_size = 0;
};

inline void lava_file_reader::read_barrier()
{
	const unsigned size = read_uint8_t();
	std::vector<unsigned> packet_indices(size);
	for (int i = 0; i < (int)size; i++)
	{
		packet_indices[i] = read_uint32_t();
		assert(packet_indices[i] != UINT32_MAX);
	}
	complete_packet();
	for (int i = 0; i < (int)size; i++)
	{
		const unsigned packet_index = packet_indices[i];
		DLOG3("Thread barrier on thread %d, waiting for packet %u on thread %d / %u", current.thread, packet_index, i, size - 1);
		const bool publish_wait = i != current.thread && packet_index > parent->thread_packet_numbers->at(i).load(std::memory_order_relaxed) && parent->cli_service.load(std::memory_order_acquire);
		if (publish_wait)
		{
			cli_wait_thread.store(i, std::memory_order_relaxed);
			cli_wait_packet.store(packet_index, std::memory_order_relaxed);
			cli_state.store(cli_thread_state::wait_barrier, std::memory_order_release);
		}
		while (i != current.thread && packet_index > parent->thread_packet_numbers->at(i).load(std::memory_order_relaxed))
		{
			if (parent->stop_requested()) throw_stop_requested();
			usleep(1);
		}
		if (publish_wait) cli_state.store(cli_thread_state::running, std::memory_order_release);
	}
	DLOG2("[t%02d] Passed thread barrier, waited for %u threads", (int)current.thread, size);
}

inline uint32_t lava_file_reader::read_handle(DEBUGPARAM(const char* name))
{
	const uint32_t index = read_uint32_t();
	const int req_thread = read_int8_t();
	const uint32_t req_packet = read_uint32_t();
	if (req_thread < 0 || req_thread == (int)current.thread)
	{
		DLOG2("[t%02d %06d] read handle %s index=%u from same thread", (int)current.thread, (int)current.packet + 1, name, (unsigned)index);
		return index;
	}
	// check for thread dependency, if we need a resource not provided yet, spin until it is
	uint32_t completed_packets = parent->thread_packet_numbers->at(req_thread).load(std::memory_order_relaxed);
#ifdef DEBUG
	if (req_packet < completed_packets) DLOG2("[t%02d %06d] read handle %s index=%u, was for tid=%d packet=%u, it is already at packet=%u", (int)current.thread, (int)current.packet + 1, name, (unsigned)index, (int)req_thread, req_packet, completed_packets);
	else DLOG2("[t%02d %06d] read handle %s index=%u, MUST WAIT for tid=%d packet=%u, it is now at packet=%u", (int)current.thread, (int)current.packet + 1, name, (unsigned)index, (int)req_thread, req_packet, completed_packets);
#endif
	const bool publish_wait = req_packet >= completed_packets && parent->cli_service.load(std::memory_order_acquire);
	if (publish_wait)
	{
		cli_wait_thread.store(req_thread, std::memory_order_relaxed);
		cli_wait_packet.store(req_packet, std::memory_order_relaxed);
		cli_state.store(cli_thread_state::wait_handle, std::memory_order_release);
	}
	while (req_packet >= completed_packets)
	{
		if (parent->stop_requested()) throw_stop_requested();
		usleep(1);
		completed_packets = parent->thread_packet_numbers->at(req_thread).load(std::memory_order_relaxed);
	}
	if (publish_wait) cli_state.store(cli_thread_state::running, std::memory_order_release);
	return index;
}

static inline bool check_cli(const callback_context& cb)
{
	lava_reader* parent = cb.reader.parent;
	const int req_thread = parent->cli_thread.load(std::memory_order_acquire);
	if (req_thread == -1) return false; // fast out if not running under CLI control
	if (parent->stop_requested()) cb.reader.throw_stop_requested();
	bool selected_thread = req_thread == cb.reader.current.thread;
	if (!selected_thread)
	{
		cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
		return false;
	}
	uint32_t completed_call = 0;
	const cli_step_mode step_mode = cb.reader.cli_step.load(std::memory_order_acquire);
	if (step_mode == cli_step_mode::calls || step_mode == cli_step_mode::function)
	{
		if (cb.reader.current.packet_type != PACKET_VULKAN_API_CALL)
		{
			cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
			return false;
		}
		if (step_mode == cli_step_mode::function && cb.reader.current.call_id != cb.reader.cli_function.load(std::memory_order_acquire))
		{
			cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
			return false;
		}
		completed_call = cb.reader.api_call_count + 1;
	}
	else
	{
		completed_call = cb.reader.cli_packet.load(std::memory_order_relaxed) + 1;
	}
	if (parent->cli_running.load(std::memory_order_acquire))
	{
		const uint32_t req_call = cb.reader.cli_call.load(std::memory_order_acquire);
		if (completed_call < req_call)
		{
			cb.reader.cli_state.store(cli_thread_state::running, std::memory_order_release);
			return false;
		}
	}
	cb.reader.cli_paused_call.store(completed_call, std::memory_order_release);
	cb.reader.cli_state.store(cli_thread_state::cli_paused, std::memory_order_release);
	cb.reader.cli_pause_generation.fetch_add(1, std::memory_order_acq_rel);
	cb.reader.cli_pause_generation.notify_all();
	parent->cli_running.store(false, std::memory_order_release);
	parent->cli_running.notify_all();
	usleep(50);
	return true; // loop in caller until lava-cli resumes replay
}

Json::Value cli_params_base_json(const callback_context& cb);
Json::Value cli_params_attachment(const callback_context& cb);
void cli_params_publish(callback_context& cb, Json::Value v);
void cli_params_unavailable(callback_context& cb);
void cli_params_packet(callback_context& cb);
void print_params_publish(callback_context& cb, Json::Value v);
void print_params_unavailable(callback_context& cb);
void print_params_packet(callback_context& cb);
